name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SERVERLESS_PLATFORM_VENDOR: tencent
  TENCENT_SECRET_ID: AKIDoSr3zf5E6i36sNcaHhqiJejX4KI0SdXC
  TENCENT_SECRET_KEY: PXOzJM9l7C1Zrsd8NM4VhcG3arseASS7
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run deploy
