name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SECRET_ID: ${{ secrets.SECRETID }}
  SECRET_KEY: ${{ secrets.SECRETKEY }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: printenv

